### ISSUE TITLE
External libraries aren't properly loading for auto complete

### ISSUE THREAD

**Issue by dbrown8674** [tcnh/FitNesseAutocompleteResponder#5]
I am getting this error when I press validate on a project that uses external jars and I'm wondering if it's a configuration issue or just not supported. Thanks for the support.
```
     [java] java.lang.NoClassDefFoundError: fixtures/ObjectProxy
     [java]     at java.lang.ClassLoader.defineClass1(Native Method)
     [java]     at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
     [java]     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
     [java]     at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
     [java]     at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
     [java]     at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
     [java]     at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
     [java]     at java.security.AccessController.doPrivileged(Native Method)
     [java]     at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
     [java]     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [java]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
     [java]     at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
     [java]     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [java]     at com.github.tcnh.fitnesse.responders.util.ClassFinder.findClasses(ClassFinder.java:56)
     [java]     at com.github.tcnh.fitnesse.responders.util.ClassFinder.getClasses(ClassFinder.java:32)
     [java]     at com.github.tcnh.fitnesse.responders.AutoCompleteResponder.addClassesToAutocompleteList(AutoCompleteResponder.java:123)
     [java]     at com.github.tcnh.fitnesse.responders.AutoCompleteResponder.getAutoCompleteDataFromPage(AutoCompleteResponder.java:81)
     [java]     at com.github.tcnh.fitnesse.responders.AutoCompleteResponder.makeResponse(AutoCompleteResponder.java:50)
     [java]     at fitnesse.FitNesseExpediter.createGoodResponse(FitNesseExpediter.java:145)
     [java]     at fitnesse.FitNesseExpediter.makeResponse(FitNesseExpediter.java:112)
     [java]     at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:51)
     [java]     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
     [java]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [java]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     [java]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     [java]     at java.lang.Thread.run(Thread.java:748)
     [java] Caused by: java.lang.ClassNotFoundException: fixtures.ObjectProxy
     [java]     at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
     [java]     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [java]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
     [java]     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [java]     ... 26 more

```

**Comment by tcnh** [comment]
As long as the jars are on slim's classpath (either by declaring using !path or !pomFile from the maven classpath plugin) and you have declared the package to use in an Import table, autocompleterespomder should be able to find them.
The validate button only executes javasript, so I think the exception happens before this

Are you using the latest version (1.0.9)? That version has a fix for an issue that caused jars with classes in their root to not be searchable.

To view the full context that autocompleteresponder builds, you can navigate to `your_testcase_url?autocomplete` in the browser. This returns a json containing all available classes, their public methods, alls scenario's and declared slim variables.

**Comment by dbrown8674** [comment]
`java.lang.InstantiationException: No responder for autocomplete`

I get this on that page. I'm using the latest version of fitnesse, the latest version of your plugin, and the latest version of the autocomplete.

When I switched auto complete version to LATEST it changed the error to this.


`     [java] java.lang.NoClassDefFoundError: fixtures/ObjectProxy
     [java]     at java.lang.ClassLoader.defineClass1(Native Method)
     [java]     at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
     [java]     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
     [java]     at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
     [java]     at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
     [java]     at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
     [java]     at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
     [java]     at java.security.AccessController.doPrivileged(Native Method)
     [java]     at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
     [java]     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [java]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
     [java]     at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
     [java]     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [java]     at com.github.tcnh.fitnesse.responders.util.ClassFinder.findClasses(ClassFinder.java:56)
     [java]     at com.github.tcnh.fitnesse.responders.util.ClassFinder.getClasses(ClassFinder.java:32)
     [java]     at com.github.tcnh.fitnesse.responders.AutoCompleteResponder.addClassesToAutocompleteList(AutoCompleteResponder.java:124)
     [java]     at com.github.tcnh.fitnesse.responders.AutoCompleteResponder.getAutoCompleteDataFromPage(AutoCompleteResponder.java:82)
     [java]     at com.github.tcnh.fitnesse.responders.AutoCompleteResponder.makeResponse(AutoCompleteResponder.java:51)
     [java]     at fitnesse.FitNesseExpediter.createGoodResponse(FitNesseExpediter.java:145)
     [java]     at fitnesse.FitNesseExpediter.makeResponse(FitNesseExpediter.java:112)
     [java]     at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:51)
     [java]     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
     [java]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [java]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     [java]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     [java]     at java.lang.Thread.run(Thread.java:748)
     [java] Caused by: java.lang.ClassNotFoundException: fixtures.ObjectProxy
     [java]     at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
     [java]     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [java]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
     [java]     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [java]     ... 26 more
`

Also this is the error that's returned when I load ?autocomplete

`     [java] java.lang.InstantiationException: No responder for autocomplete
     [java]     at fitnesse.responders.ResponderFactory.lookupResponder(ResponderFactory.java:151)
     [java]     at fitnesse.responders.ResponderFactory.makeResponder(ResponderFactory.java:129)
     [java]     at fitnesse.FitNesseExpediter.createGoodResponse(FitNesseExpediter.java:143)
     [java]     at fitnesse.FitNesseExpediter.makeResponse(FitNesseExpediter.java:112)
     [java]     at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:51)
     [java]     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
     [java]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [java]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     [java]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     [java]     at java.lang.Thread.run(Thread.java:748)
`

**Comment by tcnh** [comment]
`<version>LATEST</version>` is maven 2... was dropped in version 3. Are you sure you're getting any dependency loaded at all?

Also, did you copy the plugin to your wiki/plugins directory? (using the maven dependency plugin)
FitNesse loads plugins from there. Do you see no errors starting fitnesse?

**Comment by dbrown8674** [comment]
I refactored my dependencies that where using LATEST and it's still the same.

I switched it to `
		<dependency>
			<groupId>com.github.tcnh</groupId>
			<artifactId>fitnesse-autocomplete-responder</artifactId>
			<version>1.0.10</version>
		</dependency>`

Fitnesse looks likes it's trying to load it when it starts, and there are no errors as far as I can tell.

`main:
 [fitnesse] Starting fitnesse
     [java] Loaded responder autoComplete: com.github.tcnh.fitnesse.responders.AutoCompleteResponder
     [java] Bootstrapping FitNesse, the fully integrated standalone wiki and acceptance testing framework.
     [java] Loaded SymbolType fitnesse.wikitext.widgets.MavenClasspathSymbolType
     [java] root page: fitnesse.wiki.fs.FileSystemPage at ./FitNesseRoot#latest
     [java] logger: none
     [java] authenticator: fitnesse.authentication.OneUserAuthenticator
     [java] page factory: fitnesse.html.template.PageFactory
     [java] page theme: bootstrap-plus
     [java] Starting FitNesse on port: 8000
`

**Comment by tcnh** [comment]
So the responder loads..
How did you specify your classpath on the page? (!path...)
It seems it expects a class ObjectProxy in a package called fixtures. Is that an existing class in you project?

I'll see if I can handle this sort of exception a bit nicer, because this way one faulty import breaks the responder.

**Comment by tcnh** [comment]
I am unable to reproduce this behaviour. Are you able share a reproduction fitnesse project?

**Comment by dbrown8674** [comment]
I'm going to close this, I got moved to something else. If I have time I'll re-open it with a example project for you sorry about that.
